variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build:
  stage: build
  artifacts:
    paths:
      - build
  script:
    - mkdir build && cd build
    - cmake -DSKEPU_BUILD_EXAMPLES=ON -DSKEPU_HEADERS_ENABLE_TESTING=OFF ..
    - make
  only:
    - web
    - merge_requests

test:
  stage: test
  dependencies:
    - build
  script:
    # This should be ctest in the future, but we have no test cases that are
    # added to ctest at this point.
    - build/llvm/bin/skepu-tool --help
  only:
    - web
    - merge_requests

# vi:ts=2 sw=2 et
