before_script:
   - git submodule sync --recursive
   - git submodule update --init --recursive

stages:
  - builds
  - tests


build_skepu:
  stage: builds
  artifacts:
    paths:
    - build/bin/
  script:
    - make -j12
  when: manual
  allow_failure: false

test_skepu:
  stage: tests
  script:
    - build/bin/skepu-tool --help
  when: manual
  allow_failure: false
