variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - build_examples
  - test

build_skepu:
  stage: build
  artifacts:
    paths:
      - build/bin
  script:
    - make
  only:
    - web
    - merge_requests

build_examples:
  stage: build_examples
  dependencies:
    - build_skepu
  artifacts:
    paths:
      - examples/sequential
      - examples/parallel
  script:
    - cd examples
    - make all-sequential
    - make all-parallel
  only:
    - web
    - merge_requests

test_skepu:
  stage: test
  dependencies:
    - build_skepu
  script:
    - build/bin/skepu-tool --help
  only:
    - web
    - merge_requests

# vi:ts=2 sw=2 et
