before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ida.liu.se/".insteadOf "git@gitlab.ida.liu.se:"
  - git submodule sync --recursive
  - git submodule update --init --recursive

stages:
  - builds
  - tests


build_skepu:
  stage: builds
  artifacts:
    paths:
      - build/bin/
  script:
    - make -j12
  when: manual
  allow_failure: false

test_skepu:
  stage: tests
  script:
    - build/bin/skepu-tool --help
  when: manual
  allow_failure: false
  dependencies:
    - build_skepu
